f=open("file.txt","w")
f.write("shireen,nazneen")
f.write("\i love mom")
print("deta returune seccusfuly")
f.close()
f=open("file.txt","a")
f.write("\my mothers is beutiful")
print("deta retur seccesfully")
f.close()
f=open("file.txt","w")
list_1=["my name is shireen \n nazneen \n doughter of khairunnisa"]
f.writelines(list_1)
print("list value secsecfully")
f.close()
f=open("file.txt","r")
call=f.read()
print(call)
f.close()
p=open("file.txt","r")
call=p.read(18)
print(call)
g=open("file.txt",'r')

